In [1]:
import torch

# Forward Pass | Making A Guess

## Simple Linear Regression

Linear regression predicts a value using:

$$
\hat{y} = XW + b
$$

- **X** → input features
- **W** → weights learned by the model
- **b** → bias/intercept
- **ŷ** → predicted output

In simple terms:

> **Prediction = input × weight + bias**

W and b are two knob our model adjust

 ![The 5-step deep learning recipe](torch_5_step.png)

In [4]:
import torch

# Number of data points in our dataset
N = 10

# Each data point has:
# D_in  = number of input features
# D_out = number of output values
D_in = 1
D_out = 1

# Create random input data X
# Shape: [N, D_in] = [10, 1]
X = torch.randn(N, D_in)
print(X)

tensor([[-0.5245],
        [ 0.8218],
        [-2.2530],
        [ 1.0797],
        [ 1.1588],
        [-0.0622],
        [-1.1335],
        [ 1.3646],
        [-1.3691],
        [ 1.4890]])


In [5]:
# Create the "true" parameters used to generate our target values
# We want to create fake data that follows: y = 2x + 1
# The true relationship is: y = 2x + 1
true_W = torch.tensor([[2.0]])   # True weight
true_b = torch.tensor(1.0)       # True bias

# Generate the target values y
# X @ true_W → linear transformation (2x)
# + true_b   → adds the bias (+1)
# + random noise → makes the data slightly imperfect
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1

# The generated data approximately follows:
# y = 2x + 1
# with a small amount of random noise

print(y_true)

tensor([[ 0.0168],
        [ 2.5070],
        [-3.4367],
        [ 3.0599],
        [ 3.4865],
        [ 0.9557],
        [-1.3767],
        [ 3.6586],
        [-1.6012],
        [ 3.9092]])


# the parameters : models brain

In [9]:
# Initialize our parameters with random values.
# Shapes must be correct for matrix multiplication!

W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# the model intial hypothesis which is wrong but its ok, its start
print(f"Initial Weight W:\n {W}\n")
print(f"Initial Bias b:\n {b}")

Initial Weight W:
 tensor([[1.3515]], requires_grad=True)

Initial Bias b:
 tensor([-0.8549], requires_grad=True)


## Implementation: From Math to Code

### The Math

$$
\hat{y} = XW + b
$$

### The Code

```python
y_hat = X @ W + b

```
# Thats it, Thats the forward pass

In [10]:
import torch

# --------------------------------------------------
# Model implementation
# --------------------------------------------------

def model(X):
    # Forward pass:
    # prediction = XW + b
    return X @ W + b


# --------------------------------------------------
# Make predictions using our model
# --------------------------------------------------

y_hat = model(X)

# Compare predictions with the actual target values
print(f"Prediction y_hat (first 3 rows):\n{y_hat[:3]}\n")

print(f"True Labels y_true (first 3 rows):\n{y_true[:3]}")

Prediction y_hat (first 3 rows):
tensor([[-1.5638],
        [ 0.2557],
        [-3.8999]], grad_fn=<SliceBackward0>)

True Labels y_true (first 3 rows):
tensor([[ 0.0168],
        [ 2.5070],
        [-3.4367]])


# its terrible Prediction