# torch.nn Module

## Using NN.LINEAR


### `nn.Linear` — The Same Model, Simplified

What we built manually:

- `y_hat = X @ W + b`
- Manually calculated gradients.
- Manually updated `W` and `b` using gradient descent.

`nn.Linear(1, 1)` packages **`W` and `b` together** and PyTorch manages their gradients.

> **Our manual model → `nn.Linear` → same linear regression idea, but with PyTorch handling the parameter details.**

In [4]:
import torch

# ---------------------------------------------------------
# Training data for a simple LINEAR REGRESSION problem
# ---------------------------------------------------------

# X = input / feature values
# Each row represents one training example.
X = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])

# y_true = target / actual output values
# These are the correct answers the model should learn to predict.
#
# We generate them using the true relationship:
# y = 2x + 1
y_true = 2 * X + 1


# ---------------------------------------------------------
# Display the training data
# ---------------------------------------------------------

print("X (input features):")
print(X)

print("\ny_true (target / correct outputs):")
print(y_true)

X (input features):
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

y_true (target / correct outputs):
tensor([[ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])


# `nn.Linear` — PyTorch's Linear Layer

- **`D_in = 1`** → input has **1 feature**.
- **`D_out = 1`** → output has **1 value**.

In [6]:
# ---------------------------------------------------------
# We are now replacing our manually built linear model
# with PyTorch's built-in nn.Linear layer.
#
# Previously we manually created:
#     W = torch.randn(1, 1, requires_grad=True)
#     b = torch.randn(1, requires_grad=True)
#
# and calculated:
#     y_hat = X @ W + b
#
# nn.Linear does these parameter-management details for us.
# ---------------------------------------------------------

# Number of input features.
# Our training data X contains one feature: x.
D_in = 1

# Number of output values.
# We want the model to predict one value: y_hat.
D_out = 1


# ---------------------------------------------------------
# Create the Linear layer
# ---------------------------------------------------------
#
# This is the PyTorch equivalent of creating our W and b.
#
# nn.Linear automatically creates:
#     linear_layer.weight  -> W
#     linear_layer.bias    -> b
#
# So internally, this layer represents:
#
#     y_hat = X @ W + b
#
linear_layer = torch.nn.Linear(
    in_features=D_in,
    out_features=D_out
)


# ---------------------------------------------------------
# Look at the parameters created by PyTorch
# ---------------------------------------------------------
#
# Previously, we created W and b ourselves.
# Now PyTorch creates them automatically.
#
# weight  -> W
# bias    -> b
#
print(f"Layer's Weight (W): {linear_layer.weight}\n")
print(f"Layer's Bias (b): {linear_layer.bias}\n")


# ---------------------------------------------------------
# Forward pass
# ---------------------------------------------------------
#
# Previously we manually wrote:
#
#     y_hat = X @ W + b
#
# Now nn.Linear performs the same operation internally.
#
# X contains our input values.
# linear_layer(X) produces the model's predictions (y_hat).
#
# If X has shape [5, 1]:
#     5 = number of training examples
#     1 = number of features per example
#
y_hat_nn = linear_layer(X)


# Display a few predictions
# These are the model's current predictions BEFORE training.
print(f"Output of nn.Linear (first 3 rows):\n{y_hat_nn[:3]}")


# ---------------------------------------------------------
# KEY IDEA
# ---------------------------------------------------------
#
# Manual version:
#
#     W, b
#     y_hat = X @ W + b
#
# PyTorch version:
#
#     linear_layer = nn.Linear(1, 1)
#     y_hat = linear_layer(X)
#
# nn.Linear does not change the underlying mathematics.
# It simply packages W, b, and the X @ W + b operation
# into a reusable PyTorch layer.
# ---------------------------------------------------------

Layer's Weight (W): Parameter containing:
tensor([[-0.3465]], requires_grad=True)

Layer's Bias (b): Parameter containing:
tensor([0.9417], requires_grad=True)

Output of nn.Linear (first 3 rows):
tensor([[ 0.5952],
        [ 0.2486],
        [-0.0979]], grad_fn=<SliceBackward0>)


# What Is a Parameter?

A **parameter** is a value inside the model that the model **learns during training**.

For our linear model:

$$
\hat{y} = XW + b
$$

- **`W` (weight)** → controls how strongly `X` affects the prediction.
- **`b` (bias)** → shifts the prediction up or down.
- During training, PyTorch adjusts **`W`** and **`b`** to reduce the loss.

In our manual implementation, we created these parameters ourselves:

```python
W = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Linear Models Have a Limitation

A linear model can only learn a **straight-line relationship**.

For example:

$$
y = 2x + 1
$$

This works very well for data that roughly follows a straight line.

But imagine the real relationship looks like:

$$
y = x^2
$$

or forms a curve, circle, or other complicated pattern.

A single linear layer cannot learn these shapes.

### Important Limitation

Even if we stack multiple linear layers:

```text
Linear → Linear → Linear → Linear

```

without a non-linear activation function, the overall result is still equivalent to one larger linear transformation.

So:
```
Linear + Linear + Linear = still linear
```

The model is still limited to learning straight-line relationships.


# Why Do Neural Networks Need Non-Linearity?

Neural networks become powerful when we add **non-linear activation functions** between linear layers.

For example:

```text
Input
  ↓
Linear
  ↓
ReLU
  ↓
Linear
  ↓
ReLU
  ↓
Linear
  ↓
Output

# `nn.ReLU` (Rectified Linear Unit)

The rule is dead simple:

> If an input is **negative**, make it **zero**.

The formula is:

$$
\text{ReLU}(x) = \max(0, x)
$$


In [7]:
relu = torch.nn.ReLU()

sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])

activated_data = relu(sample_data)

print(f"Original Data:     {sample_data}")
print(f"Data after ReLU:   {activated_data}")

Original Data:     tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after ReLU:   tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])


# `nn.GELU` (Gaussian Error Linear Unit)

`GELU` is a popular **non-linear activation function**, especially in modern Transformer models such as GPT and Llama.

Unlike ReLU, GELU does **not simply turn negative values into zero**.

Instead, it applies a **smooth curve** to the input.

> **GELU = a smoother, gently curving version of ReLU.**


In [8]:
gelu = torch.nn.GELU()

sample_data = torch.tensor([-2.0, -0.5, 0.0, 0.5, 2.0])

activated_data = gelu(sample_data)

print(f"Original Data:   {sample_data}")
print(f"Data after GELU: {activated_data}")

Original Data:   tensor([-2.0000, -0.5000,  0.0000,  0.5000,  2.0000])
Data after GELU: tensor([-0.0455, -0.1543,  0.0000,  0.3457,  1.9545])


# `nn.Softmax`

`nn.Softmax` is commonly used for the **final output layer** of a classification model.

It converts the model's raw output values, called **logits**, into a **probability distribution**.

### What does Softmax do?

```text
Logits → Softmax → Probabilities
```

For example:

```text
Logits:
[2.0, 1.0, 0.1]

        ↓ Softmax

Probabilities:
[0.659, 0.242, 0.099]
```

The probabilities:

- are between **0 and 1**
- add up to **1**
- represent how confident the model is about each class

### Why do we use it?

Suppose a model is classifying an image into:

```text
Cat
Dog
Horse
```

The final linear layer might produce:

```text
[2.5, 1.2, 0.3]
```

These are **logits**, not probabilities.

After Softmax:

```text
Cat   → 0.72
Dog   → 0.20
Horse → 0.08
```

Now we can interpret the output as probabilities.

> **Softmax converts logits → probability distribution.**

### Important

`Softmax` is generally used for **multi-class classification** when we want probabilities for the possible classes.

In many PyTorch classification models, you may **not explicitly add Softmax** when using `CrossEntropyLoss`, because `CrossEntropyLoss` internally handles the required log-softmax operation.

```text
Linear layer
     ↓
   Logits
     ↓
CrossEntropyLoss
     ↓
   Loss
```

# `nn.Softmax` in Action

```python
softmax = torch.nn.Softmax(dim=-1)

# Raw model scores (logits) for 2 items,
# across 4 possible classes
logits = torch.tensor([
    [1.0, 3.0, 0.5, 1.5],
    [-1.0, 2.0, 1.0, 0.0]
])

# Convert logits into probabilities
probabilities = softmax(logits)

print(f"Output Probabilities:\n{probabilities}\n")

# Check that the probabilities for item 1 add up to 1
print(
    f"Sum of probabilities for item 1: "
    f"{probabilities[0].sum()}"
)
```

### Output

```text
Output Probabilities:

tensor([
    [0.1150, 0.6558, 0.0543, 0.1749],
    [0.0263, 0.5855, 0.2155, 0.1727]
])

Sum of probabilities for item 1: 1.0
```

### Understanding the result

For the first item, the model produced these logits:

```text
[1.0, 3.0, 0.5, 1.5]
```

The highest logit is `3.0`.

After applying Softmax:

```text
[0.1150, 0.6558, 0.0543, 0.1749]
```

The class with the highest probability is therefore the class corresponding to the highest logit:

```text
3.0 → 0.6558
```

### Key idea

```text
Raw model output
      ↓
    Logits
      ↓
   Softmax
      ↓
Probabilities
```

Each row represents one item, and the probabilities in each row add up to approximately `1`.

> **Softmax turns the model's raw scores (logits) into probabilities that we can interpret as confidence across the classes.**

In [10]:
softmax = torch.nn.Softmax(dim=-1)

# Raw model scores (logits) for 2 items,
# across 4 possible classes
logits = torch.tensor([
    [1.0, 3.0, 0.5, 1.5],
    [-1.0, 2.0, 1.0, 0.0]
])

# Convert logits into probabilities
probabilities = softmax(logits)

print(f"Output Probabilities:\n{probabilities}\n")

# Check that the probabilities for item 1 add up to 1
print(
    f"Sum of probabilities for item 1: "
    f"{probabilities[0].sum()}"
)

Output Probabilities:
tensor([[0.0939, 0.6942, 0.0570, 0.1549],
        [0.0321, 0.6439, 0.2369, 0.0871]])

Sum of probabilities for item 1: 1.0


# `nn.Embedding`

`nn.Embedding` converts **words (or tokens) → numbers** that a neural network can work with.

It is essentially a **learnable lookup table**.

### Key idea

```text
Word / Token
     ↓
  Embedding
     ↓
Numeric Vector
```

Each word gets its own **learnable vector**.

For example:

```text
"cat"  → [0.21, -0.45, 0.73]
"dog"  → [0.18, -0.39, 0.68]
"car"  → [-0.62, 0.11, 0.25]
```

The vectors are **not manually assigned**.

The model learns these numbers during training.

### Why is this useful?

Neural networks cannot directly perform mathematical operations on words such as:

```text
"cat"
"dog"
"car"
```

So we first represent each token as a vector:

```text
cat → [0.21, -0.45, 0.73]
dog → [0.18, -0.39, 0.68]
car → [-0.62, 0.11, 0.25]
```

These vectors can then be passed into the neural network.

> **`nn.Embedding` = a learnable lookup table that maps token IDs to vectors.**

# `nn.Embedding` in Code

```python
# Number of unique words/tokens in our vocabulary
vocab_size = 10

# Number of values used to represent each word
# Each word will be represented by a 3-dimensional vector
embedding_dim = 3

# Create the embedding layer
# This creates a learnable lookup table of:
#     10 words × 3 numbers per word
embedding_layer = torch.nn.Embedding(
    vocab_size,
    embedding_dim
)

# Input: a sentence represented using token IDs
#
# Each number represents a word in our vocabulary.
# For example:
#     1 → word with ID 1
#     5 → word with ID 5
#     0 → word with ID 0
#     8 → word with ID 8
#
# Shape: [1, 4]
#     1 sentence × 4 tokens
input_ids = torch.tensor([[1, 5, 0, 8]])

# Look up the vector for each token ID
word_vectors = embedding_layer(input_ids)

print(f"Input Token IDs (shape {input_ids.shape}):")
print(input_ids)

print(f"\nOutput Word Vectors (shape {word_vectors.shape}):")
print(word_vectors)
```

### What happened?

The embedding layer created a **learnable lookup table**:

```text
Vocabulary
   ↓
10 unique token IDs
   ↓
Each token has a 3-dimensional vector
```

For the input:

```text
[1, 5, 0, 8]
```

PyTorch looks up four rows from the embedding table:

```text
ID 1 → [vector for ID 1]
ID 5 → [vector for ID 5]
ID 0 → [vector for ID 0]
ID 8 → [vector for ID 8]
```

So the input shape changes from:

```text
[1, 4]
```

to:

```text
[1, 4, 3]
```

Meaning:

```text
1 sentence
    ×
4 tokens
    ×
3 numbers per token
```

### Important

The vectors are **learnable parameters**.

They start with initial values, and during training the model adjusts them using **gradient descent**, just like the `W` and `b` parameters we manually updated earlier.

> **`nn.Embedding` = a learnable lookup table that converts token IDs into vectors.**

In [12]:
import torch

# ============================================================
# 1. CREATE A VOCABULARY
# ============================================================
#
# A vocabulary is simply a collection of unique words/tokens
# that our model knows about.
#
# Here we create a very small vocabulary manually.
#
# Each word/token is assigned a unique integer ID.
#
# In a real NLP system, a tokenizer creates these IDs for us.
# ============================================================

vocab = {
    "cat": 0,
    "dog": 1,
    "runs": 2,
    "eats": 3,
    "the": 4,
    "food": 5,
    "is": 6,
    "happy": 7,
    "big": 8,
    "small": 9
}

# Number of unique tokens in our vocabulary
vocab_size = len(vocab)

print("Vocabulary:")
print(vocab)

print("\nVocabulary size:")
print(vocab_size)


# ============================================================
# 2. WHAT IS A TOKEN?
# ============================================================
#
# A token is a piece of text that the model works with.
#
# For this simple example, we are treating each word as one
# token.
#
# For example:
#
#     "the cat runs"
#
# becomes:
#
#     "the" → token
#     "cat" → token
#     "runs" → token
#
# Using our vocabulary:
#
#     "the"  → ID 4
#     "cat"  → ID 0
#     "runs" → ID 2
#
# Therefore:
#
#     "the cat runs"
#          ↓
#     [4, 0, 2]
# ============================================================


# ============================================================
# 3. CHOOSE THE EMBEDDING SIZE
# ============================================================
#
# Each token will be represented by a vector of 3 numbers.
#
# Example:
#
#     "cat" → [0.21, -0.45, 0.73]
#
# The number 3 is called the embedding dimension.
# ============================================================

embedding_dim = 3


# ============================================================
# 4. CREATE THE EMBEDDING TABLE
# ============================================================
#
# torch.nn.Embedding creates a learnable lookup table.
#
#     vocab_size   = 10
#     embedding_dim = 3
#
# Therefore the table contains:
#
#     10 rows × 3 columns
#
# Each row belongs to one token ID.
#
#     Row 0 → vector for "cat"
#     Row 1 → vector for "dog"
#     Row 2 → vector for "runs"
#     ...
#     Row 9 → vector for "small"
#
# The numbers are initially generated automatically.
# During training, these numbers can be learned/updated.
# ============================================================

embedding_layer = torch.nn.Embedding(
    num_embeddings=vocab_size,
    embedding_dim=embedding_dim
)


# ============================================================
# 5. LOOK AT THE EMBEDDING TABLE
# ============================================================
#
# The embedding table is stored in:
#
#     embedding_layer.weight
#
# Its shape is:
#
#     [10, 3]
#
# meaning:
#
#     10 tokens
#     ×
#     3 numbers per token
# ============================================================

print("\nEmbedding table:")
print(embedding_layer.weight)

print("\nEmbedding table shape:")
print(embedding_layer.weight.shape)


# ============================================================
# 6. CONVERT A SENTENCE INTO TOKEN IDs
# ============================================================
#
# Suppose our sentence is:
#
#     "the cat runs"
#
# Using our vocabulary:
#
#     "the"  → 4
#     "cat"  → 0
#     "runs" → 2
#
# Therefore the sentence becomes:
#
#     [4, 0, 2]
#
# These IDs are what we give to nn.Embedding.
# ============================================================

sentence = ["the", "cat", "runs"]

input_ids = torch.tensor([
    [vocab[word] for word in sentence]
])

print("\nSentence:")
print(sentence)

print("\nToken IDs:")
print(input_ids)

print("\nInput shape:")
print(input_ids.shape)


# ============================================================
# 7. LOOK UP THE EMBEDDINGS
# ============================================================
#
# nn.Embedding now uses each token ID as a row number.
#
#     ID 4 → look up row 4
#     ID 0 → look up row 0
#     ID 2 → look up row 2
#
# The result is a vector for every token.
# ============================================================

word_vectors = embedding_layer(input_ids)

print("\nWord vectors:")
print(word_vectors)

print("\nWord vectors shape:")
print(word_vectors.shape)


# ============================================================
# 8. UNDERSTANDING THE SHAPE
# ============================================================
#
# input_ids shape:
#
#     [1, 3]
#
#     1 = number of sentences
#     3 = number of tokens in the sentence
#
# word_vectors shape:
#
#     [1, 3, 3]
#
#     1 = number of sentences
#     3 = number of tokens
#     3 = numbers used to represent each token
#
# So:
#
#     [1, 3]
#          ↓ Embedding
#     [1, 3, 3]
#
# Each token ID has been replaced by a 3-dimensional vector.
# ============================================================


# ============================================================
# THE COMPLETE IDEA
# ============================================================
#
# Vocabulary:
#
#     "cat"  → 0
#     "dog"  → 1
#     "runs" → 2
#     ...
#
# Sentence:
#
#     "the cat runs"
#
# Token IDs:
#
#     [4, 0, 2]
#
# Embedding lookup:
#
#     4 → embedding vector for "the"
#     0 → embedding vector for "cat"
#     2 → embedding vector for "runs"
#
# Final result:
#
#     [vector_for_the,
#      vector_for_cat,
#      vector_for_runs]
#
# IMPORTANT:
#
# nn.Embedding does NOT understand the meaning of "cat" or
# "dog" by itself.
#
# It simply looks up the vector associated with each ID.
#
# The vectors become meaningful because they can be learned
# during neural-network training.
#
#     Token → ID → Embedding Vector
#
# This is why nn.Embedding can be thought of as a
# LEARNABLE LOOKUP TABLE.
# ============================================================

Vocabulary:
{'cat': 0, 'dog': 1, 'runs': 2, 'eats': 3, 'the': 4, 'food': 5, 'is': 6, 'happy': 7, 'big': 8, 'small': 9}

Vocabulary size:
10

Embedding table:
Parameter containing:
tensor([[ 1.7585, -0.1283,  0.3097],
        [ 0.8513, -0.5361, -1.0683],
        [ 0.1571, -1.8075, -0.8091],
        [-0.0387, -0.9213, -0.0778],
        [ 0.6696, -0.0513,  1.7539],
        [-0.6759, -0.8608, -1.0734],
        [ 1.3530, -0.1925, -0.6825],
        [-0.1052, -0.2256,  1.4485],
        [-1.7368,  1.1389, -1.3767],
        [-0.4665,  0.2924, -0.6809]], requires_grad=True)

Embedding table shape:
torch.Size([10, 3])

Sentence:
['the', 'cat', 'runs']

Token IDs:
tensor([[4, 0, 2]])

Input shape:
torch.Size([1, 3])

Word vectors:
tensor([[[ 0.6696, -0.0513,  1.7539],
         [ 1.7585, -0.1283,  0.3097],
         [ 0.1571, -1.8075, -0.8091]]], grad_fn=<EmbeddingBackward0>)

Word vectors shape:
torch.Size([1, 3, 3])


# `torch.nn.Embedding` — Learnable Lookup Table

`torch.nn.Embedding` behaves somewhat like a hash/lookup table, but more accurately it is a **learnable lookup table**.

Token ID → Lookup → Learned Vector

Example:

    ID 0 → [0.2, -0.7, 0.4]
    ID 1 → [-0.4, 0.1, 0.8]
    ID 2 → [0.6, 0.3, -0.2]

If the input is:

    input_ids = torch.tensor([1, 5, 0, 8])

PyTorch simply retrieves:

    1 → vector for ID 1
    5 → vector for ID 5
    0 → vector for ID 0
    8 → vector for ID 8

## `nn.Embedding` vs Vector-Search Embedding

### `nn.Embedding`

- Integer ID → vector
- Learnable lookup table
- One vector per token/ID
- Direct row lookup
- Used inside neural networks

### Vector-search embedding model

- Text → vector
- Neural network
- Vector represents text/meaning
- Computes embedding from input
- Used for semantic search/vector databases

## Key Difference

`nn.Embedding`:

> "Given this ID, retrieve its learned vector."

Vector-search embedding model:

> "Given this text, compute a vector that represents its meaning."

So `nn.Embedding` is a **basic building block for converting discrete token IDs into continuous numerical vectors** that a neural network can process.

# `nn.LayerNorm`

`nn.LayerNorm` helps keep the values flowing through a neural network in a **stable range**.

### Why do we need it?

As a neural network becomes deeper, values can sometimes become:

- **Too large** → exploding values / unstable training
- **Too small** → vanishing values / weak gradients

`LayerNorm` normalizes the values so they stay in a more **stable and predictable range**.

### What does it do?

Conceptually:

    Input values
         ↓
    Calculate mean and variance
         ↓
    Normalize the values
         ↓
    Scale and shift using learnable parameters
         ↓
    Stable output

So instead of allowing activations to continuously grow or shrink as they pass through many layers, `LayerNorm` keeps them well-behaved.

### Why is it important?

`LayerNorm` is especially important in **deep neural networks and Transformers**, where many layers are stacked together.

> **LayerNorm helps keep the internal values stable, making deep networks easier to train.**

# `nn.LayerNorm`

`nn.LayerNorm` is used to **normalize the values within each feature vector**.

It helps keep the values in a **stable numerical range**, which makes training deep neural networks more stable.

### Why do we need LayerNorm?

During neural network training, values can sometimes become:

- Very large → **exploding values**
- Very small → **vanishing values**
- Unstable from one layer to another

Layer Normalization helps by rescaling the values so that they have approximately:

- **Mean ≈ 0**
- **Standard deviation ≈ 1**

This is especially important in **deep neural networks and Transformers**.

---

## `nn.LayerNorm` in Code

```python
# Our word vectors have a feature dimension of 3.
#
# For example, one word/token might be represented as:
#
# [1.0, 2.0, 3.0]
#
# Here, the feature dimension is 3.

norm_layer = torch.nn.LayerNorm(
    normalized_shape=3
)


# Example input features
#
# Shape:
# [1, 2, 3]
#
# 1 batch
# 2 tokens
# 3 features per token
#
# Token 1 → [1.0, 2.0, 3.0]
# Token 2 → [4.0, 5.0, 6.0]

input_features = torch.tensor([
    [
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ]
])


# Apply LayerNorm
#
# LayerNorm normalizes the last dimension.
#
# Therefore, each 3-dimensional feature vector
# is normalized independently.
#
# [1, 2, 3] → normalized
# [4, 5, 6] → normalized

normalized_features = norm_layer(input_features)


print("Normalized Features:")
print(normalized_features)


# Check the mean of each feature vector.
#
# The mean should be approximately 0.

print(
    f"Mean (should be ~0): "
    f"{normalized_features.mean(dim=-1)}"
)


# Check the standard deviation.
#
# The population standard deviation is approximately 1.
#
# NOTE:
# torch.std() uses unbiased=True by default, so with only
# 3 values it reports approximately 1.2247 instead of 1.
#
# If we use unbiased=False, we get approximately 1.

print(
    f"Std Dev (population, should be ~1): "
    f"{normalized_features.std(dim=-1, unbiased=False)}"
)
```

## Example

Input:

```text
[1.0, 2.0, 3.0]
```

LayerNorm calculates:

```text
Mean = (1 + 2 + 3) / 3
     = 2
```

It then measures how far each value is from the mean and rescales them.

The resulting values are approximately:

```text
[-1.2247, 0.0000, 1.2247]
```

The important point is that the **relative differences are preserved**, but the values are put into a more stable numerical range.

---

## What does `normalized_shape=3` mean?

```python
torch.nn.LayerNorm(normalized_shape=3)
```

means:

> "Normalize the last dimension, which contains 3 features."

For example:

```text
Token 1 → [1.0, 2.0, 3.0]
Token 2 → [4.0, 5.0, 6.0]
```

Each token's feature vector is normalized independently.

```text
             Feature 1   Feature 2   Feature 3
Token 1         1.0         2.0         3.0
                 ↓           ↓           ↓
              normalize this vector
                 ↓
             -1.2247       0.0       1.2247


             Feature 1   Feature 2   Feature 3
Token 2         4.0         5.0         6.0
                 ↓           ↓           ↓
              normalize this vector
                 ↓
             -1.2247       0.0       1.2247
```

---

## LayerNorm in a Transformer

A simplified Transformer block often looks like:

```text
Input
  ↓
LayerNorm
  ↓
Attention
  ↓
LayerNorm
  ↓
Feed Forward Network
  ↓
Output
```

LayerNorm helps keep the values flowing through these many operations **numerically stable**.

### Simple intuition

Think of LayerNorm as a **volume control knob**.

If the values become too loud:

```text
1000, 1200, 900, ...
```

LayerNorm brings them back to a manageable range.

If the values become extremely small:

```text
0.00001, 0.00002, ...
```

LayerNorm rescales them into a useful range.

It does **not** simply throw away the information. It mainly keeps the numerical scale under control.

In [13]:
# Our word vectors have a feature dimension of 3.
#
# For example, one word/token might be represented as:
#
# [1.0, 2.0, 3.0]
#
# Here, the feature dimension is 3.

norm_layer = torch.nn.LayerNorm(
    normalized_shape=3
)


# Example input features
#
# Shape:
# [1, 2, 3]
#
# 1 batch
# 2 tokens
# 3 features per token
#
# Token 1 → [1.0, 2.0, 3.0]
# Token 2 → [4.0, 5.0, 6.0]

input_features = torch.tensor([
    [
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ]
])


# Apply LayerNorm
#
# LayerNorm normalizes the last dimension.
#
# Therefore, each 3-dimensional feature vector
# is normalized independently.
#
# [1, 2, 3] → normalized
# [4, 5, 6] → normalized

normalized_features = norm_layer(input_features)


print("Normalized Features:")
print(normalized_features)


# Check the mean of each feature vector.
#
# The mean should be approximately 0.

print(
    f"Mean (should be ~0): "
    f"{normalized_features.mean(dim=-1)}"
)


# Check the standard deviation.
#
# The population standard deviation is approximately 1.
#
# NOTE:
# torch.std() uses unbiased=True by default, so with only
# 3 values it reports approximately 1.2247 instead of 1.
#
# If we use unbiased=False, we get approximately 1.

print(
    f"Std Dev (population, should be ~1): "
    f"{normalized_features.std(dim=-1, unbiased=False)}"
)

Normalized Features:
tensor([[[-1.2247,  0.0000,  1.2247],
         [-1.2247,  0.0000,  1.2247]]], grad_fn=<NativeLayerNormBackward0>)
Mean (should be ~0): tensor([[0., 0.]], grad_fn=<MeanBackward1>)
Std Dev (population, should be ~1): tensor([[1.0000, 1.0000]], grad_fn=<StdBackward0>)


# `nn.Dropout`

**Purpose:** Prevents **overfitting** and helps the neural network learn more robust representations.

### How Dropout Works

During **training**, Dropout randomly sets some neuron outputs to **zero**.

```text
Input
  ↓
Linear Layer
  ↓
Dropout
  ↓
Next Layer
```

For example, suppose a layer produces:

```text
[0.8, 1.2, 0.5, 2.1, 0.9]
```

Dropout might randomly deactivate some neurons:

```text
[0.8, 0.0, 0.5, 0.0, 0.9]
```

The exact neurons that are zeroed are chosen **randomly for each training step**.

### Why Do We Do This?

Without Dropout, the network may become too dependent on particular neurons.

It can effectively **memorize the training data** instead of learning general patterns.

Dropout forces the network to distribute the learning across many neurons.

Therefore:

> **Dropout makes the network less dependent on individual neurons and more robust.**

### Important: Training vs Inference

Dropout is active during **training**:

```text
Training:
Some neurons → randomly turned OFF
```

During **inference/evaluation**, Dropout is disabled:

```text
Inference:
All neurons → active
```

PyTorch automatically handles this when using:

```python
model.train()
```

and:

```python
model.eval()
```

### Simple Analogy

Imagine a team of 10 employees.

If the same 2 employees always do all the important work, the team becomes dependent on them.

With Dropout, during training, we randomly make some employees unavailable for each task.

This forces the **entire team to learn how to contribute**.

So:

> **Dropout = randomly remove some neurons during training → prevents over-reliance → reduces overfitting → improves generalization.**

### PyTorch

```python
dropout = torch.nn.Dropout(p=0.5)
```

Here:

```text
p = 0.5
```

means each neuron has a **50% probability of being dropped** during training.

Note that PyTorch scales the remaining activations during training so that the expected activation magnitude stays consistent between training and inference.

### Key Takeaway

```text
Dropout
   ↓
Randomly zero some neuron outputs during training
   ↓
Network cannot rely too heavily on specific neurons
   ↓
Learns more distributed/robust representations
   ↓
Reduces overfitting
```

# `nn.Dropout`: Training vs. Evaluation Mode

The most important thing to remember:

> **Dropout is active only during training.**

---

## Example

```python
dropout_layer = torch.nn.Dropout(p=0.5)

# Create an input tensor containing ten 1s
input_tensor = torch.ones(1, 10)


# ----------------------------------------
# Training mode
# ----------------------------------------

# Activate dropout
dropout_layer.train()

output_during_train = dropout_layer(input_tensor)


# ----------------------------------------
# Evaluation / inference mode
# ----------------------------------------

# Deactivate dropout
dropout_layer.eval()

output_during_eval = dropout_layer(input_tensor)
```

---

## What happens during training?

We created:

```python
dropout_layer = torch.nn.Dropout(p=0.5)
```

The value:

```text
p = 0.5
```

means that each element has a **50% probability of being dropped (set to zero)** during training.

For example:

```text
Input:

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```

One possible dropout result:

```text
[0, 2, 2, 0, 0, 0, 2, 2, 0, 2]
```

Notice something important:

The surviving `1`s became `2`s.

This is because PyTorch uses **inverted dropout scaling**.

With:

```text
p = 0.5
```

the probability of keeping a value is:

```text
keep probability = 1 - p
                = 1 - 0.5
                = 0.5
```

The surviving values are divided by the keep probability:

```text
1 / 0.5 = 2
```

Therefore:

```text
1 → 0        # dropped
1 → 2        # kept and scaled
```

This scaling keeps the **expected magnitude of the activations approximately unchanged**.

---

## What happens during evaluation?

When we call:

```python
dropout_layer.eval()
```

Dropout is disabled.

The layer behaves like an identity function:

```text
Input:

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Output:

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
```

No neurons are randomly removed.

No scaling is applied.

---

## Training vs Evaluation

```text
                    TRAINING             EVALUATION
                       │                     │
                       ▼                     ▼
                 dropout.train()      dropout.eval()
                       │                     │
                       ▼                     ▼
              Randomly zero values       Nothing dropped
                       │                     │
                       ▼                     ▼
              Scale remaining values       Output unchanged
                       │                     │
                       ▼                     ▼
                 Used to learn          Used for prediction
```

---

## Why is Dropout disabled during inference?

During training, we intentionally make the network work with different subsets of neurons.

This encourages the network to learn **robust patterns** instead of depending too heavily on particular neurons.

But during inference, we want the model to use **all of its learned capacity**.

Therefore:

```text
Training:
Some neurons are randomly disabled
        ↓
Network learns robust representations

Inference:
All neurons are available
        ↓
Network makes the prediction
```

---

## Important PyTorch Concept

`train()` and `eval()` do **not** mean:

```text
train()  → start training
eval()   → start prediction
```

They primarily tell PyTorch which **behavioral mode** the model's layers should use.

For example:

```python
model.train()
```

enables training-specific behavior such as:

- Dropout randomly dropping activations
- BatchNorm using batch statistics and updating running statistics

While:

```python
model.eval()
```

switches those layers to inference behavior.

### Typical usage

```python
# Training
model.train()

for X, y in dataloader:
    output = model(X)
    loss = loss_function(output, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


# Evaluation / inference
model.eval()

with torch.no_grad():
    output = model(X)
```

---

## Key Takeaway

```text
nn.Dropout(p=0.5)

TRAINING:
    Randomly drop ~50% of activations
    ↓
    Scale the surviving activations
    ↓
    Prevent over-reliance on individual neurons
    ↓
    Reduce overfitting


EVALUATION:
    Dropout is OFF
    ↓
    All activations are used
    ↓
    No random behavior
    ↓
    Stable predictions
```

> **Dropout changes the network's behavior during training, but not during inference.**

In [17]:
import torch


# ============================================================
# 1. CREATE THE DROPOUT LAYER
# ============================================================

# p = 0.5 means:
#     50% probability of DROPPING each value
#
# Therefore:
#     Drop probability  = 0.5  (50%)
#     Keep probability  = 1-p
#                       = 1-0.5
#                       = 0.5  (50%)
#
# During training, Dropout will randomly set some values to 0.

dropout_probability = 0.5

dropout_layer = torch.nn.Dropout(
    p=dropout_probability
)


# ============================================================
# 2. CREATE INPUT DATA
# ============================================================

# Create a tensor containing 10 values.
#
# Shape:
#     [1, 10]
#
# Meaning:
#     1 row
#     10 values/features
#
# We use all 1s so that it is easy to see what Dropout does.

input_tensor = torch.ones(1, 10)

print("Original input:")
print(input_tensor)

print("\nInput shape:")
print(input_tensor.shape)


# ============================================================
# 3. TRAINING MODE
# ============================================================

# Tell the Dropout layer:
#
#     "We are currently training the neural network."
#
# In training mode, Dropout is ACTIVE.

dropout_layer.train()

print("\nDropout layer is in TRAINING mode.")


# Apply Dropout to the input.
#
# Because p=0.5:
#
#     Approximately 50% of the values will be dropped.
#
# Dropped values:
#     1 → 0
#
# Values that survive are scaled by:
#
#     1 / (1-p)
#     = 1 / 0.5
#     = 2
#
# Therefore a surviving value becomes:
#
#     1 → 2

output_during_train = dropout_layer(input_tensor)


print("\nOutput during TRAINING:")
print(output_during_train)


# ============================================================
# 4. EVALUATION / INFERENCE MODE
# ============================================================

# Tell the Dropout layer:
#
#     "We are evaluating the trained neural network."
#
# In evaluation mode, Dropout is DISABLED.

dropout_layer.eval()

print("\nDropout layer is in EVALUATION mode.")


# Apply the same input again.
#
# Since Dropout is disabled:
#
#     Nothing is randomly removed.
#     No scaling is applied.
#
# Therefore:
#
#     1 → 1
#     1 → 1
#     1 → 1
#     ...
#
# The output is the same as the input.

output_during_eval = dropout_layer(input_tensor)


print("\nOutput during EVALUATION:")
print(output_during_eval)


# ============================================================
# 5. COMPARE THE RESULTS
# ============================================================

print("\n" + "=" * 50)
print("COMPARISON")
print("=" * 50)

print("\nOriginal:")
print(input_tensor)

print("\nDuring training:")
print(output_during_train)

print("\nDuring evaluation:")
print(output_during_eval)

Original input:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Input shape:
torch.Size([1, 10])

Dropout layer is in TRAINING mode.

Output during TRAINING:
tensor([[0., 0., 0., 2., 2., 0., 2., 0., 2., 2.]])

Dropout layer is in EVALUATION mode.

Output during EVALUATION:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

COMPARISON

Original:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

During training:
tensor([[0., 0., 0., 2., 2., 0., 2., 0., 2., 2.]])

During evaluation:
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


# PyTorch: `nn.Module` and `torch.optim`

PyTorch provides two core abstractions that clean up neural-network training code:

1. `nn.Module` → organizes the model
2. `torch.optim` → automates parameter updates during learning

---

## 1. The "From Scratch" Training Loop

Without `torch.optim`, we would manually update every parameter:

```python
with torch.no_grad():
    W -= learning_rate * W.grad
    b -= learning_rate * b.grad

W.grad.zero_()
b.grad.zero_()
```

The problem is that a real neural network may have:

- 50 layers
- Millions of parameters
- Many different weights and biases

We don't want to manually write update and gradient-reset code for every parameter.

---

## 2. `nn.Module` — Organizing the Model

Think of `nn.Module` as the **instruction booklet and baseplate for our LEGO model**.

It provides a standard structure for:

- defining layers
- connecting layers
- storing learnable parameters
- organizing the complete neural network

For example:

```python
class MyModel(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = torch.nn.Linear(10, 20)
        self.layer2 = torch.nn.Linear(20, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)

        return x
```

Because the layers are registered inside `nn.Module`, PyTorch can automatically find their parameters:

```python
model.parameters()
```

So instead of manually keeping track of every `W` and `b`, PyTorch knows which tensors are trainable parameters.

---

## 3. `torch.optim` — Updating the Parameters

Think of `torch.optim` as the **skilled builder** who knows exactly how to adjust all the LEGO bricks according to the gradients.

For example:

```python
optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)
```

Now the optimizer knows:

- which parameters to update
- the learning rate
- which optimization algorithm to use

During training:

```python
loss.backward()

optimizer.step()

optimizer.zero_grad()
```

These three lines replace much of the manual parameter-update code.

---

## 4. Connecting Everything Together

```text
                 Neural Network
                       |
                       v
                  nn.Module
                       |
          +------------+------------+
          |                         |
        Layers                  Parameters
          |                         |
          |                    W1, b1, W2, b2...
          |                         |
          +------------+------------+
                       |
                       v
                   Forward
                       |
                       v
                      Loss
                       |
                       v
                loss.backward()
                       |
                       v
                   Gradients
                       |
                       v
                 torch.optim
                       |
                       v
              optimizer.step()
                       |
                       v
             Updated Parameters
```

---

## 5. The Complete Training Loop

Putting the pieces together:

```python
model = MyModel()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

for x, y in training_data:

    # 1. Forward pass
    prediction = model(x)

    # 2. Calculate how wrong the prediction is
    loss = loss_function(prediction, y)

    # 3. Calculate gradients
    loss.backward()

    # 4. Update all model parameters
    optimizer.step()

    # 5. Clear old gradients
    optimizer.zero_grad()
```

---

## 6. The Important Connection

```text
nn.Module
    ↓
Organizes and exposes all model parameters
    ↓
model.parameters()
    ↓
torch.optim
    ↓
Uses the gradients to update those parameters
```

So:

- `nn.Module` answers: **"What is my model and what parameters does it have?"**
- `loss.backward()` answers: **"How should each parameter change to reduce the loss?"**
- `torch.optim` answers: **"How exactly should I update those parameters?"**

This is why we don't need to write millions of lines of code to update millions of parameters.

# The Model Blueprint: `nn.Module`

`nn.Module` is the base class used to define and organize PyTorch neural-network models.

## Inherit from `torch.nn.Module`

We create our own model class by inheriting from `torch.nn.Module`:

```python
class MyModel(torch.nn.Module):
    ...
```

This gives our model all the functionality provided by PyTorch's `nn.Module`.

---

## `__init__()` — Define the Layers

The `__init__()` method is where we **define the layers and components** of our model.

```python
class MyModel(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.layer1 = torch.nn.Linear(10, 20)
        self.layer2 = torch.nn.Linear(20, 1)
```

Think:

```text
__init__()
    ↓
What components/layers does my model have?
```

For example:

```text
Input
  ↓
Layer 1
  ↓
Layer 2
  ↓
Output
```

---

## `forward()` — Connect the Layers

The `forward()` method defines **how data flows through those layers**.

```python
def forward(self, x):

    x = self.layer1(x)
    x = self.layer2(x)

    return x
```

Think:

```text
forward()
    ↓
How does data move through my model?
```

So the two methods have different responsibilities:

```text
__init__()
    ↓
Define WHAT the model contains
    ↓
Layers / parameters


forward()
    ↓
Define HOW data flows
    ↓
Layer 1 → Layer 2 → Layer 3 → Output
```

---

## Complete Example

```python
import torch


class MyModel(torch.nn.Module):

    def __init__(self):
        super().__init__()

        # Define the layers
        self.layer1 = torch.nn.Linear(10, 20)
        self.layer2 = torch.nn.Linear(20, 1)

    def forward(self, x):

        # Connect the layers
        x = self.layer1(x)
        x = self.layer2(x)

        return x


# Create the model
model = MyModel()


# Input: batch of 5 samples,
# each sample contains 10 features
x = torch.randn(5, 10)


# Run the input through the model
output = model(x)

print(output.shape)
```

Output:

```text
torch.Size([5, 1])
```

---

## Why `super().__init__()`?

```python
super().__init__()
```

initializes the underlying `torch.nn.Module`.

This is important because PyTorch needs to set up the machinery that allows it to:

- track layers
- track trainable parameters
- move the model to CPU/GPU
- switch between training and evaluation modes
- expose parameters through `model.parameters()`

For example:

```python
model.parameters()
```

can now find the weights and biases inside:

```text
layer1
    ↓
weights + bias

layer2
    ↓
weights + bias
```

---

## The Big Picture

```text
                nn.Module
                    |
                    v
              Your Model
                    |
          +---------+---------+
          |                   |
       __init__()          forward()
          |                   |
          v                   v
    Define layers       Connect layers
          |                   |
          v                   v
    Parameters          Data flow
          |                   |
          +---------+---------+
                    |
                    v
             model.parameters()
                    |
                    v
              torch.optim
                    |
                    v
            Update parameters
```

### Remember

```text
__init__() → WHAT does my model contain?

forward()  → HOW does data flow through my model?
```

In [21]:
import torch.nn as nn


# ---------------------------------------------------------
# Define our own neural network model
# ---------------------------------------------------------
# nn.Module is the base class for PyTorch neural network models.
# By inheriting from it, PyTorch can automatically track:
# - layers
# - parameters
# - gradients
# - train/eval mode
#
class LinearRegressionModel(nn.Module):

    # -----------------------------------------------------
    # Constructor: define the layers used by our model
    # -----------------------------------------------------
    def __init__(self, in_features, out_features):

        # Initialize the parent nn.Module class.
        # This is required so PyTorch can properly register
        # our layers and parameters.
        super().__init__() # super imp

        # Create a fully-connected (linear) layer.
        #
        # in_features  = number of input values
        # out_features = number of output values
        #
        # For example:
        #   nn.Linear(1, 1)
        #
        # means:
        #   1 input  ->  1 output
        #
        # Internally this layer learns:
        #   y = xW + b
        #
        # where W = weight
        #       b = bias
        #
        self.linear_layer = nn.Linear(
            in_features,
            out_features
        )

    # -----------------------------------------------------
    # Forward pass: define how input moves through model
    # -----------------------------------------------------
    def forward(self, x):

        # x enters the linear layer.
        #
        # The linear layer performs:
        #
        #     output = xW + b
        #
        # PyTorch automatically tracks the operations so
        # gradients can later be calculated during training.
        return self.linear_layer(x)


# ---------------------------------------------------------
# Create an instance of our model
# ---------------------------------------------------------
#
# One input feature:
#     x = [some value]
#
# One output feature:
#     y = [predicted value]
#
model = LinearRegressionModel(
    in_features=1,
    out_features=1
)

print("Model Architecture")
print(model)

Model Architecture
LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)


In [22]:
import torch
import torch.nn as nn
import torch.optim as optim


# ---------------------------------------------------------
# Hyperparameters
# ---------------------------------------------------------
# Learning rate controls how large each parameter update is.
learning_rate = 0.01


# ---------------------------------------------------------
# Create the optimizer
# ---------------------------------------------------------
# Adam is a commonly used optimization algorithm.
#
# model.parameters() gives Adam access to all learnable
# parameters (weights and biases) inside our model.
#
# Adam will use the gradients of these parameters to decide
# how they should be updated to reduce the loss.
optimizer = optim.Adam(
    model.parameters(),
    lr=learning_rate
)


# ---------------------------------------------------------
# Create the loss function
# ---------------------------------------------------------
# MSELoss = Mean Squared Error
#
# It measures the difference between:
#     predicted output
# and
#     actual/target output
#
# The optimizer then uses the gradients of this loss
# to update the model parameters.
loss_fn = nn.MSELoss()

In [24]:
epochs = 1000

for epoch in range(epochs):
    ### FORWARD PASS ###
    y_hat = model(X)

    ### CALCULATE LOSS ###
    loss = loss_fn(y_hat, y_true)

    ### THE THREE-LINE MANTRA ###
    # 1. Zero the gradients
    optimizer.zero_grad()

    # 2. Compute gradients
    loss.backward()

    # 3. Update the parameters
    optimizer.step()

    # Optional: Print progress
    if epoch % 10 == 0:
        print(f"Epoch {epoch:02d}: Loss={loss.item():.4f}")

Epoch 00: Loss=21.8278
Epoch 10: Loss=19.0278
Epoch 20: Loss=16.5333
Epoch 30: Loss=14.3204
Epoch 40: Loss=12.3657
Epoch 50: Loss=10.6465
Epoch 60: Loss=9.1414
Epoch 70: Loss=7.8296
Epoch 80: Loss=6.6917
Epoch 90: Loss=5.7093
Epoch 100: Loss=4.8651
Epoch 110: Loss=4.1432
Epoch 120: Loss=3.5289
Epoch 130: Loss=3.0087
Epoch 140: Loss=2.5703
Epoch 150: Loss=2.2026
Epoch 160: Loss=1.8956
Epoch 170: Loss=1.6406
Epoch 180: Loss=1.4296
Epoch 190: Loss=1.2559
Epoch 200: Loss=1.1134
Epoch 210: Loss=0.9969
Epoch 220: Loss=0.9020
Epoch 230: Loss=0.8250
Epoch 240: Loss=0.7625
Epoch 250: Loss=0.7119
Epoch 260: Loss=0.6709
Epoch 270: Loss=0.6377
Epoch 280: Loss=0.6107
Epoch 290: Loss=0.5886
Epoch 300: Loss=0.5704
Epoch 310: Loss=0.5552
Epoch 320: Loss=0.5425
Epoch 330: Loss=0.5316
Epoch 340: Loss=0.5221
Epoch 350: Loss=0.5138
Epoch 360: Loss=0.5063
Epoch 370: Loss=0.4994
Epoch 380: Loss=0.4930
Epoch 390: Loss=0.4870
Epoch 400: Loss=0.4812
Epoch 410: Loss=0.4756
Epoch 420: Loss=0.4702
Epoch 430: Loss

 ![The Three Step Mantras](three_step_mantras.png)