In [1]:
import torch

/Users/surendrashukla/projects/2026/platform-lab/pytorch_exploration/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


# Tensors
Tensors are the building block of PyTorch — every input, weight, activation, and gradient is a tensor.

In [13]:
# pattern 1.  Python list to Tensor
data = [
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
    [1, 1, 0, 1, 0, 0, 1, 0, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
    [1, 0, 0, 1, 1, 1, 1, 0, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
    [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]
]
tensors = torch.tensor(data)
print(tensors)

tensor([[0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
        [1, 1, 0, 1, 0, 0, 1, 0, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
        [1, 0, 0, 1, 1, 1, 1, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
        [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]])


In [14]:
# pattern 2 creating from disired shape
# you need shape you need but not the weight, this is how you initialize model weights
shape = (2, 3) # a shape tuple for 2 rows and three columns
ones = torch.ones(shape)
zeros = torch.zeros(shape)
random= torch.randn(shape)

print("Ones Tensor", ones)
print("Zeros Tensor", zeros)
print("Random Tensor", random)

Ones Tensor tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random Tensor tensor([[-1.3852,  2.0303,  0.2812],
        [-0.3151,  1.9750, -2.3023]])


In [17]:
# pattern 3 creation by mimicking another tensor
# you need a new tensors with exact shape and size
template =  torch.tensor([[1, 2],[3, 4]])
rand_like = torch.randn_like(template, dtype=torch.float)
print("template Tensor", template)
print("rand_like Tensor", rand_like)

template Tensor tensor([[1, 2],
        [3, 4]])
rand_like Tensor tensor([[-1.0634, -1.0946],
        [-1.6779,  0.5033]])


# whats inside Tensor
shape, size, device

In [18]:
tensor = torch.randn(2, 3)
print(tensor.shape) # 90% of errors are shape mismatch
print(tensor.dtype) # data type of numbers
print(tensor.device) # where does tensor live

torch.Size([2, 3])
torch.float32
cpu


default is torch.float32 because of gradient which needs very tiny nudges these nudges are done by AutoGrad

# AutoGrad
- stands for automatic differenciation
- its torch built in gradiet calculator
- your model parameters (weights and biases) must be a float type. float32 is standard
data that represents categories or count can be integers
- it requires to activate by using `requires_grade = True`

- by default a tensor is just data to tell pytorch its learnable parameter you must set `requires_grade = True`. the most important setting in all the pytorch.
- it send a message to AutoGrade engine: "this is parameter. from now on, track every single operation that happens to it"


# data vs parameters


In [19]:
import torch

# A standard data tensor
x_data = torch.tensor([[1., 2.],
                       [3., 4.]])

# A parameter tensor (we need gradients)
w = torch.tensor([[1.0],
                  [2.0]], requires_grad=True)

print(f"Data tensor requires_grad: {x_data.requires_grad}")
print(f"Parameter tensor requires_grad: {w.requires_grad}")

Data tensor requires_grad: False
Parameter tensor requires_grad: True


once we do requires_grad: True it start a live recording on tensors

# Builing the graph
Goal: compute z = x.y , where y = a + b

In [22]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

y = a + b
z= x * y

print(z) # pytorch create graph for for each operation

tensor(20., grad_fn=<MulBackward0>)


In [24]:
print(z.grad_fn) # print graph for z
print(y.grad_fn) # print graph for y
print(a.grad_fn) # None since it was not created by 

None


In [26]:
def print_graph(fn, indent=0):
    if fn is None:
        return

    print(" " * indent + str(fn))

    for next_fn, _ in fn.next_functions:
        print_graph(next_fn, indent + 4)


print_graph(z.grad_fn)  # grad_fn is breadcrumb

## Tensor: Noun
## Autograd: the nervouse system

## We need operations (the verbs of torch)/ Action / calculation

## * vs @

In [27]:
import torch

# Element-wise multiplication
# Each element is multiplied with the corresponding element.

a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [10, 20],
    [30, 40]
])

# Element-wise multiplication
result = a * b

print("a:")
print(a)

print("\nb:")
print(b)

print("\na * b:")
print(result)

a:
tensor([[1, 2],
        [3, 4]])

b:
tensor([[10, 20],
        [30, 40]])

a * b:
tensor([[ 10,  40],
        [ 90, 160]])


In [30]:
# 2. Matrix multiplication — @ Pwers nural network Linear algebra rule

import torch

m1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

m2 = torch.tensor([
    [10, 20],
    [30, 40],
    [50, 60]
])

print("m1 shape:", m1.shape)
print("m2 shape:", m2.shape)

result = m1 @ m2

print("\nm1 @ m2:")
print(result)

print("\nResult shape:", result.shape)

m1 shape: torch.Size([2, 3])
m2 shape: torch.Size([3, 2])

m1 @ m2:
tensor([[220, 280],
        [490, 640]])

Result shape: torch.Size([2, 2])


## to build a linear layer using classic formula y = xw + b we use @

## Reduction operation and dim operator

sum | mean | maximum